# Generated by Django 3.2.9 on 2022-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ticklist',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
