# Generated by Django 3.2.9 on 2021-11-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210817_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
            ],
            options={
                'verbose_name': 'Подзачада',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['created'],
            },
        ),
    ]
