# Generated by Django 3.2.9 on 2021-11-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ticklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticklist',
            options={'verbose_name': 'Подзачада', 'verbose_name_plural': 'Подзадачи'},
        ),
    ]
