# Generated by Django 3.2.9 on 2021-11-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ticklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_ticks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='number_of_ticks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ticklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticklist', to='base.task'),
        ),
    ]
